INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(1, 'Cesar', 'Carvajal', 'cesar@gmail.com', '2019-09-20', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(2, 'David', 'Pabon', 'david@gmail.com', '2019-10-20', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Javier', 'Moncada', 'javier@gmail.com', '2018-10-18', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Brayan', 'Espitia', 'espitia@gmail.com', '2020-09-28', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Jarbir', 'Mejia', 'jarbir@gmail.com', '2020-10-26', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('camilo', 'boada', 'camilo@gmail.com', '2017-10-18', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('gerson', 'ortiz', 'gerson@gmail.com', '2019-09-07', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('adrian', 'garcia', 'adrian@gmail.com', '2020-04-18', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Brandon', 'Garcia', 'brandon@gmail.com', '2019-11-28', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Carlos', 'Pablos', 'carlos@gmail.com', '2018-10-03', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Tom', 'Hardy', 'tom@gmail.com', '2016-12-20', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Pepito', 'Perez', 'pepito@gmail.com', '2020-09-15', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Leo', 'Dicaprio', 'leo@gmail.com', '2014-10-26', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Sebastian', 'Hernandez', 'sebas@gmail.com', '2016-02-18', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Andres', 'Gelves', 'andres@gmail.com', '2015-11-07', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('John', 'Cardenas', 'john@gmail.com', '2015-04-18', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Nelson', 'Gamboa', 'nelson@gmail.com', '2011-11-18', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Al', 'Pacino', 'pacino@gmail.com', '2008-10-03', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Quentin', 'Tarantino', 'tarantinp@gmail.com', '2007-11-03', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Brad', 'Pitt', 'pitt@gmail.com', '2019-10-13', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Celmira', 'Pabon', 'celmira@gmail.com', '2010-11-15', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('James', 'Rodriguez', 'james@gmail.com', '2008-10-03', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Chester', 'Bennigton', 'chester@gmail.com', '2017-06-23', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Martha', 'Chacin', 'martha@gmail.com', '2017-04-13', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Diana', 'Leon', 'diana@gmail.com', '2018-07-19', '');
INSERT INTO `clientes` (nombre, apellido, email, create_at, foto) VALUES('Robert', 'Deniro', 'deniro@gmail.com', '1999-10-26', '');

INSERT INTO `productos` (nombre, precio, create_at) VALUES('Panasonic Pantalla LCD', '700000', NOW());
INSERT INTO `productos` (nombre, precio, create_at) VALUES('Xiaomi Celular 64GB', '600000', NOW());
INSERT INTO `productos` (nombre, precio, create_at) VALUES('Apple iPod Shuffle', '800000', NOW());
INSERT INTO `productos` (nombre, precio, create_at) VALUES('HP Computador Portatil', '1500000', NOW());
INSERT INTO `productos` (nombre, precio, create_at) VALUES('Sony Camara Digital', '1000000', NOW());
INSERT INTO `productos` (nombre, precio, create_at) VALUES('Sony Audifonos SuperBass', '200000', NOW());
INSERT INTO `productos` (nombre, precio, create_at) VALUES('Samsung TV SMART 42"', '1500000', NOW());