INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES(1, 'Cesar', 'Carvajal', 'cesar@gmail.com', '2019-09-20');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES(2, 'David', 'Pabon', 'david@gmail.com', '2019-10-20');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Javier', 'Moncada', 'javier@gmail.com', '2018-10-18');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Brayan', 'Espitia', 'espitia@gmail.com', '2020-09-28');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Jarbir', 'Mejia', 'jarbir@gmail.com', '2020-10-26');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('camilo', 'boada', 'camilo@gmail.com', '2017-10-18');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('gerson', 'ortiz', 'gerson@gmail.com', '2019-09-07');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('adrian', 'garcia', 'adrian@gmail.com', '2020-04-18');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Brandon', 'Garcia', 'brandon@gmail.com', '2019-11-28');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Carlos', 'Pablos', 'carlos@gmail.com', '2018-10-03');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Tom', 'Hardy', 'tom@gmail.com', '2016-12-20');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Pepito', 'Perez', 'pepito@gmail.com', '2020-09-15');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Leo', 'Dicaprio', 'leo@gmail.com', '2014-10-26');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Sebastian', 'Hernandez', 'sebas@gmail.com', '2016-02-18');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Andres', 'Gelves', 'andres@gmail.com', '2015-11-07');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('John', 'Cardenas', 'john@gmail.com', '2015-04-18');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Nelson', 'Gamboa', 'nelson@gmail.com', '2011-11-18');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Al', 'Pacino', 'pacino@gmail.com', '2008-10-03');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Quentin', 'Tarantino', 'tarantinp@gmail.com', '2007-11-03');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Brad', 'Pitt', 'pitt@gmail.com', '2019-10-13');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Celmira', 'Pabon', 'celmira@gmail.com', '2010-11-15');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('James', 'Rodriguez', 'james@gmail.com', '2008-10-03');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Chester', 'Bennigton', 'chester@gmail.com', '2017-06-23');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Martha', 'Chacin', 'martha@gmail.com', '2017-04-13');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Diana', 'Leon', 'diana@gmail.com', '2018-07-19');
INSERT INTO `clientes` (nombre, apellido, email, create_at) VALUES('Robert', 'Deniro', 'deniro@gmail.com', '1999-10-26');